"""Train a YOLO pose model on the vase Figure-Pose keypoint dataset.

The committed V7 used the generic COCO `yolov8n-pose.pt`, which only fires on
real human bodies and returns zeros on most vase imagery. This script instead
fine-tunes a pose model on the supervisor's vase keypoint annotations
(`Figure-Pose`, 17 keypoints) so extract_features.py can produce meaningful
figure poses for retrieval.

The shipped dataset has only a `train` split (images/train, labels/train) and a
`train.txt` whose `data/images/...` prefix does not match the real layout, so we
ignore train.txt and build our own deterministic train/val lists from the actual
image files (YOLO finds each label by swapping `images` -> `labels`).
"""

import argparse
import random
from pathlib import Path

from common import SEED, IMAGE_EXTS, project_root

# COCO-style 17-keypoint left/right swap, used for horizontal-flip augmentation.
COCO_FLIP_IDX = [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="v7_pose/assets/pose_dataset/train_and_valid_final",
                        help="Folder containing images/train and labels/train")
    parser.add_argument("--base-model", default="yolo11n-pose.pt",
                        help="Pretrained pose checkpoint to fine-tune from")
    parser.add_argument("--output-dir", default="runs/pose_model",
                        help="Where the trained weights + data.yaml are written")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--val-frac", type=float, default=0.15)
    return parser.parse_args()


def list_images(images_dir):
    files = [p for p in images_dir.rglob("*") if p.suffix.lower() in IMAGE_EXTS]
    return sorted(files, key=lambda p: p.name.lower())


def write_yaml(path, train_txt, val_txt):
    flip = ", ".join(str(i) for i in COCO_FLIP_IDX)
    path.write_text(
        "# Auto-generated by train_pose.py — do not edit by hand.\n"
        f"train: {train_txt}\n"
        f"val: {val_txt}\n"
        "kpt_shape: [17, 3]\n"
        f"flip_idx: [{flip}]\n"
        "names:\n"
        "  0: Figure-Pose\n",
        encoding="utf-8",
    )


def main():
    args = parse_args()
    base = project_root()
    dataset = base / args.dataset
    images_dir = dataset / "images"
    if not images_dir.is_dir():
        raise FileNotFoundError(f"No images/ under dataset: {dataset}")

    out_dir = base / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    images = list_images(images_dir)
    if not images:
        raise FileNotFoundError(f"No images found under {images_dir}")

    # deterministic train/val split (absolute paths; YOLO maps images->labels)
    random.seed(SEED)
    shuffled = images[:]
    random.shuffle(shuffled)
    n_val = max(1, int(args.val_frac * len(shuffled)))
    val_imgs = shuffled[:n_val]
    train_imgs = shuffled[n_val:]
    print(f"Dataset: {len(images)} images -> {len(train_imgs)} train / {len(val_imgs)} val")

    train_txt = out_dir / "pose_train.txt"
    val_txt = out_dir / "pose_val.txt"
    train_txt.write_text("\n".join(str(p) for p in train_imgs), encoding="utf-8")
    val_txt.write_text("\n".join(str(p) for p in val_imgs), encoding="utf-8")

    data_yaml = out_dir / "pose_data.yaml"
    write_yaml(data_yaml, train_txt, val_txt)
    print(f"Wrote data config: {data_yaml}")

    from ultralytics import YOLO

    print(f"Fine-tuning {args.base_model} for {args.epochs} epochs...")
    model = YOLO(args.base_model)
    model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        seed=SEED,
        project=str(out_dir),
        name="train",
        exist_ok=True,
    )

    best = out_dir / "train" / "weights" / "best.pt"
    target = out_dir / "pose_best.pt"
    if best.exists():
        target.write_bytes(best.read_bytes())
        print(f"Done. Trained pose weights: {target}")
    else:
        print(f"WARNING: expected weights not found at {best}")


if __name__ == "__main__":
    main()
